version: "2.4"

services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: jenkins
    ports:
    -  9090:8080
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
  dockerregistry:
    image: registry:2
    container_name: dockerregistry
    ports:
    -  5000:5000
